# Use root/example as user/password credentials
version: '2.10'

services:
  mariadb:
    container_name: mariadb_local
    image: mariadb:11.0-rc
    volumes:
      - ./db/conf.d:/etc/mysql/conf.d
      - ./db/init.d:/docker-entrypoint-initdb.d
    ports:
      - "3306:3306"
    environment:
      MARIADB_ROOT_PASSWORD: ${DATABASE_ROOT_PASSWORD}
      MARIADB_DATABASE: "pharmacy-explorer"
      MARIADB_USER: ${DATABASE_USERNAME}
      MARIADB_PASSWORD: ${DATABASE_PASSWORD}
      TZ: "Asia/Seoul"
  redis:
    container_name: redis_local
    image: redis:7
    ports:
      - "6379:6379"
    environment:
      TZ: "Asia/Seoul"