spring:
  datasource:
    driver-class-name: org.mariadb.jdbc.Driver
    url: jdbc:mariadb://localhost:3306/pharmacy-explorer
    username: ${DATABASE_USERNAME}
    password: ${DATABASE_PASSWORD}
  redis:
    host: ${PHARMACY_REDIS_HOST}
    port: ${PHARMACY_REDIS_PORT}
  jpa:
    hibernate:
      ddl-auto: validate

kakao:
  api-key: ${KAKAO_REST_API_KEY}
---
spring:
  config:
    activate:
      on-profile: test
  datasource:
    driver-class-name: org.testcontainers.jdbc.ContainerDatabaseDriver
    url: jdbc:tc:mariadb:11:///pharmacy-explorer
  redis:
    host: localhost
    port: 6379
  jpa:
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        format_sql: true
    show-sql: true