name: Deploy to cloudtype
on:
  push:
    branches:
      - main
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Connect deploy key
        uses: cloudtype-github-actions/connect@v1
        with:
          token: ${{ secrets.CLOUDTYPE_TOKEN }}
          ghtoken: ${{ secrets.GHP_TOKEN }}
      - name: Deploy
        uses: cloudtype-github-actions/deploy@v1
        with:
          token: ${{ secrets.CLOUDTYPE_TOKEN }}
          project: pharmacy-explorer-app/pharmacy-explorer-app
          stage: main
          yaml: |
            name: pharmacy-explorer
            app: java@11
            options:
              ports: 8080
              env:
                - name: SPRING_PROFILES_ACTIVE
                  value: prod
                - name: PHARMACY_EXPLORER_DB_URL
                  var: PHARMACY_EXPLORER_DB_URL
                - name: DATABASE_USERNAME
                  secret: DATABASE_USERNAME
                - name: DATABASE_PASSWORD
                  secret: DATABASE_PASSWORD
                - name: PHARMACY_REDIS_HOST
                  var: PHARMACY_REDIS_HOST
                - name: PHARMACY_REDIS_PORT
                  var: PHARMACY_REDIS_PORT
                - name: KAKAO_REST_API_KEY
                  secret: KAKAO_REST_API_KEY
            context:
              git:
                url: https://github.com/GuardJo/pharmacy-explorer.git
                ref: ${{ github.ref }}
              preset: java-springboot
